/*


 Boom , a javascript loader and manager

 MIT License

 https://github.com/dexbol/boom

*/
if(typeof CN6!="undefined")var _CN6=CN6;var CN6=function(){if(!(this instanceof CN6))return new CN6;this._init()};
(function(h){function v(a,b){var c=q;c=c[a]?c[a].fullpath:a;var e=c.indexOf(".css")>-1?"css":"js",d=o[a];if(e=="css"){b=document.createElement("link");b.setAttribute("href",c);b.setAttribute("type","text/css");b.setAttribute("rel","stylesheet");s.parentNode.insertBefore(b,s)}else{d||(d=o[a]={handler:[b?b:null]});if(d.status==t)b&&b(a);else if(d.status==A)b&&d.handler.push(b);else{var g=document.createElement("script");g.src=c;g.async=false;g.onload=g.onreadystatechange=function(){if(!this.readyState||
this.readyState=="loaded"||this.readyState=="complete"){d.status=t;for(var f=d.handler,i;f.length>0;)(i=f.shift())&&i(a);g.load=g.onreadystatechange=null}};s.parentNode.insertBefore(g,s);d.status=A}}}function B(a,b){if(a)for(var c=0,e=a.length,d=e,g,f=function(){d--;if(d==0&&b){b();f=a=b=d=null}};c<e;c++){g=a[c];v(g,f)}}function F(a){if(G)for(var b=C(a,true),c=b.shift();c;){v(c,b.length==0?function(){w(a,true)}:null);c=b.shift()}else{b=C(a);var e=function(){if(b.length==0){w(a,true);a=e=b=null}else B(b.shift(),
e)};B(b.shift(),e)}}function C(a,b){for(var c=a.loadList,e=q,d=[],g=[],f=0,i=c.length,l={},j=0,k=[],m=function(r){var x=e[r].requires;if(l[r]!=true){if(x)for(var H=x.length,y=0;y<H;y++)m(x[y]);g.push(r);k.push(r);l[r]=true}};f<i;f++){m(c[f]);d.push(g);j=Math.max(j,g.length);g=[];l={}}if(b)return a.loadList=k;b=[];var u;for(f=0;f<j;f++){c=[];for(var z=0;z<i;z++)if((u=d[z][f])&&!l[u]){c.push(u);l[u]=true}b.push(c);l={}}return a.loadList=b}function w(a,b){var c=a.loadList,e=a.waitList,d=a.args;b=b?e:
d;d=0;for(var g=b.length,f=h.Env.mods,i={},l=function(j){if(j)if(!i[j]){i[j]=true;if(D(j))o[j]&&o[j].status==t||c.push(j);else{var k=f[j];if(k){if(k&&k.details.requires){j=k.details.requires.length;for(var m=0;m<j;m++)l(k.details.requires[m])}}else{k=I(j);if(o[k]&&o[k].status==t)throw new Error("\u6587\u4ef6\u7684\u6a21\u5757\u63cf\u8ff0\u4fe1\u606f\u4e0e\u6587\u4ef6\u5185\u5b9e\u9645\u6dfb\u52a0\u7684\u6a21\u5757\u4e0d\u4e00\u81f4\u3002INFO : "+j);if(k){if(!i[k]){c.push(k);i[k]=true}e.push(j)}}}}};d<
g;d++)l(b[d]);c.length>0?F(a):J(a)}function J(a){var b=a.args,c=a.context,e=a.callback,d=[],g=0,f=b.length,i=h.Env.mods;for(p=function(l){var j=i[l];if(j&&j.details.requires)for(var k=j.details.requires.length,m=0;m<k;m++)p(j.details.requires[m]);D(l)||d.push(l)};g<f;g++)p(b[g]);c._attach(d);e&&e(c);h.Env[a.id]=null}function I(a){var b=q;for(var c in b)if(b.hasOwnProperty(c))for(var e=b[c].mods||[],d=0;d<e.length;d++)if(e[d]==a)return c;return false}function D(a){if(a.indexOf(".js")>-1||a.indexOf(".css")>
-1||a.indexOf(".php")>-1)return true;return false}function E(a){if(!a)return false;return Object.prototype.toString.call(a)=="[object Object]"}var q={},n,o={};n=document;var G=n.createElement("script").async===true||"MozAppearance"in n.documentElement.style||window.opera,s=n.getElementsByTagName("script")[0],A=1,t=2;n={_init:function(){if(!h.Env)h.Env={mods:{},_attached:{},_used:{},_guidp:"ROOMS6-SEED-",_cidx:0,_scripts:o,_meta:q};if(!this.Env)this.Env={_used:{},_attached:{}}},guid:function(){return h.Env._guidp+
++h.Env._cidx},add:function(a,b,c){h.Env.mods[a]={name:a,fn:b,details:c||{}};c&&c.use===true&&this.use(a);return this},addFile:function(a,b){if(typeof a=="object")for(var c in a)a.hasOwnProperty(c)&&this.addFile(c,a[c]);q[a]=b},load:v,use:function(){var a=Array.prototype.slice.call(arguments,0),b=a.length,c=this.guid();b=typeof a[b-1]=="function"?a.pop():null;h.Env[c]={id:c,callback:b,args:a,waitList:[],loadList:[],ret:[],context:this};w(h.Env[c])},_attach:function(a){for(var b=a.length,c=h.Env.mods,
e=this.Env._attached,d=0;d<b;d++)if(!e[a[d]]){c[a[d]].fn(this);e[a[d]]=true}},mix:function(a,b,c,e,d,g){if(!b||!a)return a||this;if(d)switch(d){case 1:return h.mix(a.prototype,b.prototype,c,e,0,g);case 2:h.mix(a.prototype,b.prototype,c,e,0,g);break;case 3:return h.mix(a,b.prototype,c,e,0,g);case 4:return h.mix(a.prototype,b,c,e,0,g);default:}var f,i;if(e&&e.length){f=0;for(d=e.length;f<d;++f){i=e[f];if(b.hasOwnProperty(i))if(g&&E(a[i]))h.mix(a[i],b[i]);else if(c||!(i in a))a[i]=b[i]}}else for(f in b)if(b.hasOwnProperty(f))if(g&&
E(a[f]))h.mix(a[f],b[f],c,e,0,true);else if(c||!(f in a))a[f]=b[f];return a},merge:function(){var a=arguments,b={},c,e=a.length;for(c=0;c<e;c+=1)h.mix(b,a[c],true,0,true);return b},extend:function(a,b,c,e){if(!b||!a)return a;var d=Object.prototype,g=b.prototype,f=function(i){function l(){}l.prototype=i;return new l}(g);a.prototype=f;f.constructor=a;a.superclass=g;if(b!==Object&&g.constructor===d.constructor)g.constructor=b;c&&h.mix(f,c,true);e&&h.mix(a,e,true);return a}};h.prototype=n;for(p in n)h[p]=
n[p];h._init()})(CN6,window);var _BOOM_DEBUG_=false;CN6.addFile("base.js",{fullpath:_BOOM_DEBUG_?"base.source.js":"store/base_MIN_201105191833.js",mods:["util"]});CN6.load("base.js");CN6.addFile("mA_mB_mC.js",{fullpath:_BOOM_DEBUG_?"mA_mB_mC.source.js":"store/mA_mB_mC_MIN_201105191833.js",mods:["mA","mB","mC"]});CN6.addFile("mD.js",{fullpath:_BOOM_DEBUG_?"mD.source.js":"store/mD_MIN_201105191833.js",mods:["mD"]});
CN6.addFile("mE.js",{fullpath:_BOOM_DEBUG_?"mE.source.js":"store/mE_MIN_201105191833.js",mods:["mE"]});
